feat: add openApiDocument to module-loader Context #968
pmcelhaney/counterfact pull request #1144
Opened 2024-12-27 18:21 UTC by mgrigoriev8109

I *think* this change passes the openApiDocument over from the `app.ts` file to the `module-loader.ts`. Wasn't 100% sure how to test this change locally though, so I'd love to do that if someone can help me wrap my head around it.

2024-12-27 19:37 UTC, dethell commented
> I _think_ this change passes the openApiDocument over from the `app.ts` file to the `module-loader.ts`. Wasn't 100% sure how to test this change locally though, so I'd love to do that if someone can help me wrap my head around it.

I'll pull this on Monday (or today if at all possible) and see how your changes look. I'll circle back on what tests need to be updated.

2024-12-29 21:50 UTC, pmcelhaney requested changes
Thank you and nice work! This looks right as far as I can tell. 

To test, reference the new argument in your _.context.ts file. If you just want to test that it worked, console.log it. 

We'll want a unit test too. I'm not sure how to approach that off the top of my head. Will look this week. 😅

2024-12-29 21:50 UTC, pmcelhaney commented on src/server/module-loader.ts
> +              openApi
Move this up one line so it's part of the object including `loadContext`. 

The idea to pass a single [parameter object](https://refactoring.guru/introduce-parameter-object) to the constructor for a Context class. We can use destructing to make the constructor's signature look like it takes a list of named arguments. 

Here's what a context class might look like. 


```js
export class Context {
   constructor({ loadContext, openApi }) {

     // grab the context object from some other path
     const otherContext = loadContext("/some/path");
    
     // read the OpenAPI document 
     const paths = openApi.paths;

     // ...
  } 
}
```

2025-06-03 20:08 UTC, dethell commented
Closing this per communication with the OP.

2025-06-03 20:08 UTC, closed without merging