Rework context
pmcelhaney/counterfact pull request #739
Opened 2024-01-20 21:55 UTC by pmcelhaney

2024-01-24 13:55 UTC, dethell submitted a review, later dismissed

2024-01-25 10:31 UTC, dethell requested changes
Nearly there. Couple changes.

2024-01-25 10:31 UTC, dethell commented on docs/usage.md
>  class PetStore {
```suggestion
export class Context {
```

2024-01-25 10:31 UTC, dethell commented on docs/usage.md
>  export default new PetStore();
```suggestion
```

2024-01-26 03:12 UTC, pmcelhaney commented
Thanks @dethell! So nice to have another pair of eyes on this stuff.

2024-01-26 10:13 UTC, dethell approved these changes
Approved with a minor nit.

2024-01-26 10:13 UTC, dethell commented on src/typescript-generator/generate.js
> +  //   repository.get("paths/$.context.ts").exportDefault(new ContextCoder(paths));
```suggestion
```
Did you mean to leave this comment?

2024-01-26 10:13 UTC, merged